### ISSUE TITLE
Unity iOS Build Error: Framework not found ARCoreBase.xcframework

### ISSUE THREAD

**Issue by zeku0909** [google-ar/arcore-unity-extensions#120]
Hello,

I am currently working on a Unity project (version 2022.2.15) targeting iOS and I'm encountering a build error when trying to build the project in Xcode. The error message is as follows:

```
Framework not found ARCoreBase.xcframework
Linker command failed with exit code 1 (use -v to see invocation)
```

I have tried various solutions, but the issue persists. Any help or suggestions on how to resolve this error would be greatly appreciated.

Thank you.

**Comment by sada913** [comment]
"I experienced the same error, but it was resolved when I cleared XCode's cache and performed 'pod install' again. During this process, please make sure that the version of arcore in the podfile is 1.37."

**Comment by zeku0909** [comment]
Thank you for the information.
However, I tried that and it didn't solve the issue. After running 'pod install', I'm getting a multitude of Undefined symbol errors related to AR. 
Then, when I attempt to 'Build And Run' from Unity again, I receive the 'Framework not found' error once more.

**Comment by zeku0909** [comment]
The issue was caused by the version specified in these files being outdated:
Assets/ExtensionsAssets
ARCoreiOSGeospatialDependencies.xml
ARCoreiOSDependencies.xml

The problem can be corrected by either entering the version number or deleting the files and reinstalling the package. After that, if the ARCore version in pod is old, perform 'pod install'.

For some reason, an error occurred stating that the AppIcon could not be found, but by creating a new one, the build was successful. 
I will consider this issue resolved. Thank you.

**Comment by alanspace** [comment]
> ssets/ExtensionsAssets
> ARCoreiOSGeospatialDependencies.xml
> ARCoreiOSDependencies.xml

I find ARCoreiOSDependencies.xml but not ARCoreiOSGeospatialDependencies.xml, are they from ARCore Extensions Sample files?  Where can I enter the version number? Do you mean reinstall ARCore Extensions package? I'm new to Unity, AR foundation or Xcode, can you let me know how can I tell if ARCore version in pod is old, and how to perform pod install? 

Thanks a lot!!
