### ISSUE TITLE
[Codelab] - Create an AR game using Unity's AR Foundation starter-package url 404: Not Found

### ISSUE THREAD

**Issue by KamikX** [google-ar/arcore-unity-extensions#45]
Hi, 
in [Codelab - Create an AR game using Unity's AR Foundation ](https://codelabs.developers.google.com/arcore-unity-ar-foundation#1) is not possible download starter-package from https://raw.githubusercontent.com/googlecodelabs/arcore-unity-arf-game/main/codelab-starter-package.unitypackage I get response 404: Not Found

Thanks.

**Comment by devbridie** [comment]
Fixed that, thank you.

**Comment by KamikX** [comment]
@devbridie thank you for quick response, unfortunately new URL still doesn't work
![Snímka obrazovky 2021-05-20 o 14 41 56](https://user-images.githubusercontent.com/2276560/118980408-be4f9500-b979-11eb-952b-ebac2b7dc233.png)

**Comment by devbridie** [comment]
Changed visibility; please give it one more try.. 🙏

**Comment by KamikX** [comment]
It's okay now :thumbsup:
